### ISSUE TITLE
Progress Bar for Deploying CF

### ISSUE THREAD

**Issue by vinayu** [pivotal-cf/cfdev#14] opened 2018-03-13 03:49 UTC
Hello,

Is there a way to add a progress bar to show the status of deploying BOSH and CF. Right now it feels like I am waiting for a long time and I do not know if its stuck or moving along.

**Comment by sclevine** [comment] 2018-03-13 13:47
Duplicate of #7

**Closed by sclevine** 2018-03-13 13:47 UTC
